# FRC 1721 Tidal Force
# 2022

# Because robotpy is so easy to use, this is moreso a
# collection of shortcuts, handy for doing simple scripts
# and macros.

all: help

help:
	@echo
	@echo "Targets:"
	@echo "   sim           Shortcut for roboy.py sim."
	@echo "   clean         Shortucut for git clean -fdX"
	@echo

sim:
	python robot.py sim

clean:
	git clean -fdX
