name: Black Formatter
on: pull_request

jobs:
  formatblack:
    name: runner / black
    runs-on: ubuntu-latest

    # Do these steps
    steps:
        # Essentially get checkout
      - uses: actions/checkout@v2

        # Actual action that runs black
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      
        # If black found any violations, annotate them with review dog (bot)
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
        
        # If annotations were necessary, you failed this check!
      - name: Fail if actions taken
        if: steps.action_black.outputs.is_formatted == 'true'
        run: exit 1

        # If you failed this check, @everyone!
      - name: Discord notification
        if: ${{ failure() }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Black formatter failed <@&614313406345904148>!'
