name: Submit Release

on:
  push:
    tags:
      - '*'

jobs:
  make_docs:
    runs-on: ubuntu-latest
    name: Build Docs
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: x64
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: sudo apt update

    - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename latexmk

    - name: Install requirements
      run: pip install -r docs/requirements.txt

    - run: cd docs && make latexpdf

    - run: mv docs/_build/latex/*.pdf docs/_build/latex/FRC1721_Robot_Manual.pdf

    - uses: actions/upload-artifact@v2
      with:
        name: Tidal_Force_Robot_Manual
        path: docs/_build/latex/FRC1721_Robot_Manual.pdf


  publish_docs:
    runs-on: ubuntu-latest
    name: Publish Docs
    needs: [make_docs]

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: Tidal_Force_Robot_Manual

    - name: Upload Docs to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: '*.pdf'
        tag: ${{ github.ref }}
        overwrite: true
        body: "Tidal Force Robotics, Automated with github ci/cd."
        file_glob: true
